version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps"
    steps:
      - checkout
      - run:
          name: Run Make
          command: 'make'
      - store_artifacts:
          path: cping
          destination: cping
