version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps"
    steps:
      - checkout
      - run:
          name: Run Make
          command: 'make'
      - run:
          name: Run cping
          command: './cping -c 5 localhost'
